<!DOCTYPE html>
<html lang="id">

<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            margin: 20px;
        }

        h2 {
            text-align: center;
            margin-bottom: 10px;
        }

        p {
            text-align: center;
            font-size: 11px;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th,
        td {
            border: 1px solid #555;
            padding: 6px 8px;
        }

        th {
            background-color: #f0f0f0;
            text-align: center;
        }

        tr:nth-child(even) {
            background-color: #fafafa;
        }

        footer {
            text-align: center;
            font-size: 10px;
            margin-top: 25px;
            color: #555;
        }
    </style>
</head>

<body>

    <x-kop-surat-cetak></x-kop-surat-cetak>
    <h2>{{ $judul }}</h2>
    <p><b>Tanggal:</b> {{ $tanggal }}</p>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Nama Siswa</th>
                <th>NIS</th>
                <th>NISN</th>
                <th>No. HP</th>
                <th>Alamat</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($alumni as $index => $row)
                <tr>
                    <td style="text-align:center;">{{ $index + 1 }}</td>
                    <td>{{ $row->nama_siswa }}</td>
                    <td>{{ $row->nis }}</td>
                    <td>{{ $row->nisn }}</td>
                    <td>{{ $row->nohp_siswa }}</td>
                    <td>{{ $row->alamat }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <footer>
        <small>Generated by MTs I'Anatul Muta'Allimin - {{ now()->format('Y') }}</small>
    </footer>
</body>

</html>
