<!DOCTYPE html>
<html lang="id">

<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
        }

        h2,
        h3 {
            text-align: center;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }

        th,
        td {
            border: 1px solid #444;
            padding: 5px 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        img.chart {
            display: block;
            margin: 0 auto 15px;
            width: 80%;
        }

        .tahun-block {
            page-break-inside: avoid;
            margin-bottom: 25px;
        }

        footer {
            text-align: center;
            font-size: 10px;
            margin-top: 30px;
        }

        .status-lulus {
            background-color: #d4edda;
        }

        .status-dropout {
            background-color: #f8d7da;
        }

        .status-aktif {
            background-color: #dbeafe;
        }

        .status-pindah {
            background-color: #fff3cd;
        }

        .status-lainnya {
            background-color: #f0f0f0;
        }
    </style>
</head>

<body>
    <x-kop-surat-cetak></x-kop-surat-cetak>
    <h2>{{ $judul }}</h2>
    {{-- <p><b>Tanggal:</b> {{ $tanggal }}</p> --}}

    @foreach ($statistik as $index => $item)
        <div class="tahun-block">
            <h3>📅 Angkatan Tahun 20{{ $item['prefix'] }} (Total: {{ $item['total'] }} siswa)</h3>

            @if ($item['chartBase64'])
                <img class="chart" src="data:image/png;base64,{{ $item['chartBase64'] }}"
                    alt="Grafik Siswa {{ $item['prefix'] }}">
            @endif

            @if ($item['total'] == 0)
                <p><i>Tidak ditemukan data.</i></p>
            @else
                <table>
                    <thead>
                        <tr>
                            <th>Status Siswa</th>
                            <th>Jumlah</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($item['data'] as $row)
                            @php
                                $class = 'status-' . strtolower($row->status_siswa);
                            @endphp
                            <tr class="{{ $class }}">
                                <td>{{ ucfirst($row->status_siswa) }}</td>
                                <td>{{ $row->jumlah }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @endif
        </div>

        @if (($index + 1) % 2 == 0)
            <div style="page-break-after: always;"></div>
        @endif
    @endforeach

    <footer>
        <small>Generated by {{$Identitas->namasek}} - {{ now()->format('Y') }}</small>
    </footer>
</body>

</html>
