<?php

namespace App\Console\Commands\Guru;

use Illuminate\Console\Command;
use App\Models\User\Guru\Detailguru;

class UpdateDetailguruCommand extends Command
{
    protected $signature = 'guru:update-data';
    protected $description = 'Memperbaharui data';

    public function handle()
    {
        $guruArray = [
            [
                'user_id' => null,
                'kelas_id' => null,
                'foto' => null,
                'kode_guru' => 'CY',
                'nama_guru' => 'Cahya Nurwenda, S.Pd',
                'nip' => null,
                'nuptk' => '3951762664110030',
                'nik' => '3329161906840000',
                'status' => 'HonorSertifikasi',
                'tahun_sertifikasi' => '2014',
                'jenis_kelamin' => 'Laki - Laki',
                'pendidikan' => 'S1',
                'lulusan' => '2007',
                'jurusan' => 'Pendidikan B. Inggris',
                'tahun_lulus' => '2007',
                'rt' => '2',
                'rw' => '8',
                'desa' => 'Kubangsari',
                'kecamatan' => 'ketanggungan',
                'kabupaten' => 'Brebes',
                'provinsi' => 'Jawa Tengah',
                'jalan' => 'Kubangsari',
                'alamat' => 'Kubangsari, Rt 2, Rw 8, Desa Kubangsari, Kecamatan ketanggungan, Kabupaten Brebes',
                'no_hp' => '628989290441',
                'agama' => 'Islam',
                'tempat_lahir' => 'Brebes',
                'tanggal_lahir' => '19/06/1984',
                'tmt_mengajar' => '16/07/2005',
            ],
            [
                'user_id' => null,
                'kelas_id' => null,
                'foto' => null,
                'kode_guru' => 'AS',
                'nama_guru' => 'ANDI SAHRUDIN, S.Pd',
                'nip' => null,
                'nuptk' => '9454764665200003',
                'nik' => '3329112211860002',
                'status' => 'GTY',
                'tahun_sertifikasi' => null,
                'jenis_kelamin' => 'Laki - Laki',
                'pendidikan' => 'S1',
                'lulusan' => '2015',
                'jurusan' => 'PJOK',
                'tahun_lulus' => '2015',
                'rt' => '6',
                'rw' => '2',
                'desa' => 'Kubangpari',
                'kecamatan' => 'Kersana',
                'kabupaten' => 'Brebes',
                'provinsi' => 'Jawa Tengah',
                'jalan' => 'Kubangpari',
                'alamat' => 'Kubangpari, Rt 6, Rw 2, Desa Kubangpari, Kecamatan Kersana, Kabupaten Brebes',
                'no_hp' => '62859148222221',
                'agama' => 'Islam',
                'tempat_lahir' => 'Brebes',
                'tanggal_lahir' => '22/11/1986',
                'tmt_mengajar' => '04/01/2006',
            ],

            [
                'user_id' => null,
                'kelas_id' => null,
                'foto' => null,
                'kode_guru' => 'IZ',
                'nama_guru' => 'IZZATUL LAILIYAH, S.Pd, ',
                'nip' => null,
                'nuptk' => '2036398818800300',
                'nik' => ' 3329166312880004',
                'status' => 'GTT',
                'tahun_sertifikasi' => null,
                'jenis_kelamin' => 'Perempuan',
                'pendidikan' => 'S1',
                'lulusan' => '2012',
                'jurusan' => 'Pendidikan Matematika',
                'tahun_lulus' => '2012',
                'rt' => '7',
                'rw' => '3',
                'desa' => 'Kubangwungu',
                'kecamatan' => 'ketanggungan',
                'kabupaten' => 'Brebes',
                'provinsi' => 'Jawa Tengah',
                'jalan' => 'Kubangwungu',
                'alamat' => 'Kubangwungu, Rt 7, Rw 3, Desa Kubangwungu, Kecamatan ketanggungan, Kabupaten Brebes',
                'no_hp' => '6282325791900',
                'agama' => 'Islam',
                'tempat_lahir' => 'Brebes',
                'tanggal_lahir' => '23/12/1988',
                'tmt_mengajar' => '02/07/2012',
            ],
            [
                'user_id' => null,
                'kelas_id' => null,
                'foto' => null,
                'kode_guru' => 'RA',
                'nama_guru' => 'RINA RETNOWATI, S.Pd, ',
                'nip' => null,
                'nuptk' => '2036398818800100',
                'nik' => '3329115801880002',
                'status' => 'GTY',
                'tahun_sertifikasi' => null,
                'jenis_kelamin' => 'Perempuan',
                'pendidikan' => 'S1',
                'lulusan' => '2010',
                'jurusan' => 'Matematika ',
                'tahun_lulus' => '2010',
                'rt' => '2',
                'rw' => '6',
                'desa' => 'Kersana',
                'kecamatan' => 'Kersana',
                'kabupaten' => 'Brebes',
                'provinsi' => 'Jawa Tengah',
                'jalan' => 'Kersana',
                'alamat' => 'Kersana, Rt 2, Rw 6, Desa Kersana, Kecamatan Kersana, Kabupaten Brebes',
                'no_hp' => '6285878106480',
                'agama' => 'Islam',
                'tempat_lahir' => 'Brebes',
                'tanggal_lahir' => '18/01/1988',
                'tmt_mengajar' => '01/07/2011',
            ],
            [
                'user_id' => null,
                'kelas_id' => null,
                'foto' => null,
                'kode_guru' => 'SZ',
                'nama_guru' => 'SITI ZAKIYAH, S.Pd,',
                'nip' => null,
                'nuptk' => '2036398819100100',
                'nik' => '3329166507910008',
                'status' => 'GTY',
                'tahun_sertifikasi' => null,
                'jenis_kelamin' => 'Perempuan',
                'pendidikan' => 'S1',
                'lulusan' => '2016',
                'jurusan' => 'Bahasa Indonesia',
                'tahun_lulus' => '2016',
                'rt' => '8',
                'rw' => '3',
                'desa' => 'Kubangwungu',
                'kecamatan' => 'ketanggungan',
                'kabupaten' => 'Brebes',
                'provinsi' => 'Jawa Tengah',
                'jalan' => 'Kubangwungu',
                'alamat' => 'Kubangwungu, Rt 8, Rw 3, Desa Kubangwungu, Kecamatan ketanggungan, Kabupaten Brebes',
                'no_hp' => '6285924325726',
                'agama' => 'Islam',
                'tempat_lahir' => 'Brebes',
                'tanggal_lahir' => '26/07/1991',
                'tmt_mengajar' => '02/07/2016',
            ],
            [
                'user_id' => null,
                'kelas_id' => null,
                'foto' => null,
                'kode_guru' => 'AU',
                'nama_guru' => 'ANNA UMISAHARA, S.Pd, ',
                'nip' => null,
                'nuptk' => ' 2036398818600100',
                'nik' => '3329114705860003',
                'status' => 'GTY',
                'tahun_sertifikasi' => null,
                'jenis_kelamin' => 'Perempuan',
                'pendidikan' => 'S1',
                'lulusan' => '2010',
                'jurusan' => 'Bahasa Inggris',
                'tahun_lulus' => '2010',
                'rt' => '5',
                'rw' => '3',
                'desa' => 'Kersana ',
                'kecamatan' => 'Kersana',
                'kabupaten' => 'Brebes',
                'provinsi' => 'Jawa Tengah',
                'jalan' => 'Kersana',
                'alamat' => 'Kersana, Rt 5, Rw 3, Desa Kersana , Kecamatan Kersana, Kabupaten Brebes',
                'no_hp' => '6281226956351',
                'agama' => 'Islam',
                'tempat_lahir' => 'Brebes',
                'tanggal_lahir' => '07/03/1986',
                'tmt_mengajar' => '02/07/2012',
            ],
            [
                'user_id' => null,
                'kelas_id' => null,
                'foto' => null,
                'kode_guru' => 'NQ',
                'nama_guru' => 'NURUL QOMARIYAH, S.Sos, ',
                'nip' => null,
                'nuptk' => '2036398819500100',
                'nik' => ' 3329164204950013',
                'status' => 'GTY',
                'tahun_sertifikasi' => null,
                'jenis_kelamin' => 'Perempuan',
                'pendidikan' => 'S1',
                'lulusan' => '2018',
                'jurusan' => 'BKI',
                'tahun_lulus' => '2018',
                'rt' => '5',
                'rw' => '3',
                'desa' => 'Dukuh Tengah',
                'kecamatan' => 'ketanggungan',
                'kabupaten' => 'Brebes',
                'provinsi' => 'Jawa Tengah',
                'jalan' => 'DukuhTengah',
                'alamat' => 'DukuhTengah, Rt 5, Rw 3, Desa Dukuh Tengah, Kecamatan ketanggungan, Kabupaten Brebes',
                'no_hp' => '628976233655',
                'agama' => 'Islam',
                'tempat_lahir' => 'Brebes',
                'tanggal_lahir' => '02/04/1995',
                'tmt_mengajar' => '12/01/2018',
            ],
            [
                'user_id' => null,
                'kelas_id' => null,
                'foto' => null,
                'kode_guru' => 'NA',
                'nama_guru' => 'NISWAH QONITA AMAR, S.Pd',
                'nip' => null,
                'nuptk' => '20363988',
                'nik' => '3329164307960000',
                'status' => 'GTY',
                'tahun_sertifikasi' => null,
                'jenis_kelamin' => 'Perempuan',
                'pendidikan' => 'S1',
                'lulusan' => '2019',
                'jurusan' => 'BAHASA ARAB',
                'tahun_lulus' => '2019',
                'rt' => '2',
                'rw' => '4',
                'desa' => 'Kersana',
                'kecamatan' => 'Kersana',
                'kabupaten' => 'Brebes',
                'provinsi' => 'Jawa Tengah',
                'jalan' => 'Kersana Timur',
                'alamat' => 'Kersana Timur, Rt 2, Rw 4, Desa Kersana, Kecamatan Kersana, Kabupaten Brebes',
                'no_hp' => '685726302470',
                'agama' => 'Islam',
                'tempat_lahir' => 'Brebes',
                'tanggal_lahir' => '03/07/1997',
                'tmt_mengajar' => null,
            ],
            [
                'user_id' => null,
                'kelas_id' => null,
                'foto' => null,
                'kode_guru' => 'IM',
                'nama_guru' => 'IMAS INTARI, S.Pd',
                'nip' => null,
                'nuptk' => '2036712710100100',
                'nik' => '3329164708010000',
                'status' => 'GTY',
                'tahun_sertifikasi' => null,
                'jenis_kelamin' => 'Perempuan',
                'pendidikan' => 'S1',
                'lulusan' => '2023',
                'jurusan' => 'PAI',
                'tahun_lulus' => '2023',
                'rt' => '8',
                'rw' => '1',
                'desa' => 'Kubangwungu',
                'kecamatan' => 'ketanggungan',
                'kabupaten' => 'Brebes',
                'provinsi' => 'Jawa Tengah',
                'jalan' => 'Kubangwungu',
                'alamat' => 'Kubangwungu, Rt 8, Rw 1, Desa Kubangwungu, Kecamatan ketanggungan, Kabupaten Brebes',
                'no_hp' => '6289673332861',
                'agama' => 'Islam',
                'tempat_lahir' => 'Brebes',
                'tanggal_lahir' => '07/08//2001',
                'tmt_mengajar' => null,
            ],
            [
                'user_id' => null,
                'kelas_id' => null,
                'foto' => null,
                'kode_guru' => 'ER',
                'nama_guru' => 'ELLA YULIA RAHMAWATI, S.Pd',
                'nip' => null,
                'nuptk' => '2036398819900200',
                'nik' => '3329165907990000',
                'status' => 'GTY',
                'tahun_sertifikasi' => null,
                'jenis_kelamin' => 'Perempuan',
                'pendidikan' => 'S1',
                'lulusan' => '2022',
                'jurusan' => 'ILMU SOSIAL',
                'tahun_lulus' => '2022',
                'rt' => '3',
                'rw' => '1',
                'desa' => 'Ketanggungan',
                'kecamatan' => 'ketanggungan',
                'kabupaten' => 'Brebes',
                'provinsi' => 'Jawa Tengah',
                'jalan' => 'Ketanggungan',
                'alamat' => 'Ketanggungan, Rt 3, Rw 1, Desa Ketanggungan, Kecamatan ketanggungan, Kabupaten Brebes',
                'no_hp' => '6285712295925',
                'agama' => 'Islam',
                'tempat_lahir' => 'Brebes',
                'tanggal_lahir' => '19/07/1999',
                'tmt_mengajar' => null,
            ],
            [
                'user_id' => null,
                'kelas_id' => null,
                'foto' => null,
                'kode_guru' => 'SA',
                'nama_guru' => 'SAMSUL ARIFIN, S.Pd.I',
                'nip' => null,
                'nuptk' => null,
                'nik' => '3329161601920000',
                'status' => 'GTY',
                'tahun_sertifikasi' => null,
                'jenis_kelamin' => 'Laki - Laki',
                'pendidikan' => 'S1',
                'lulusan' => '2015',
                'jurusan' => 'FITK',
                'tahun_lulus' => '2015',
                'rt' => '2',
                'rw' => '2',
                'desa' => 'Kubangwungu',
                'kecamatan' => 'ketanggungan',
                'kabupaten' => 'Brebes',
                'provinsi' => 'Jawa Tengah',
                'jalan' => 'Kubangwungu',
                'alamat' => 'Kubangwungu, Rt 2, Rw 2, Desa Kubangwungu, Kecamatan ketanggungan, Kabupaten Brebes',
                'no_hp' => '6289622008876',
                'agama' => 'Islam',
                'tempat_lahir' => 'Brebes',
                'tanggal_lahir' => '16/01/1992',
                'tmt_mengajar' => '01/04/2024',
            ],
            [
                'user_id' => null,
                'kelas_id' => null,
                'foto' => null,
                'kode_guru' => 'DT',
                'nama_guru' => 'DEA TRI KOMALASARI, S.Pd',
                'nip' => null,
                'nuptk' => null,
                'nik' => '3329166504000004',
                'status' => 'GTY',
                'tahun_sertifikasi' => null,
                'jenis_kelamin' => 'Perempuan',
                'pendidikan' => 'S1',
                'lulusan' => '2023',
                'jurusan' => 'TADRIS BIOLOGI',
                'tahun_lulus' => '2023',
                'rt' => '4',
                'rw' => '2',
                'desa' => 'Dukuhturi',
                'kecamatan' => 'ketanggungan',
                'kabupaten' => 'Brebes',
                'provinsi' => 'Jawa Tengah',
                'jalan' => 'Jl. KH. Mukhlas Dukuhturi',
                'alamat' => 'Jl. KH. Mukhlas Dukuhturi, Rt 4, Rw 2, Desa Dukuhturi, Kecamatan ketanggungan, Kabupaten Brebes',
                'no_hp' => '6289523640195',
                'agama' => 'Islam',
                'tempat_lahir' => 'Brebes',
                'tanggal_lahir' => '25/04/2000',
                'tmt_mengajar' => '17/04/2024',
            ],
            [
                'user_id' => null,
                'kelas_id' => null,
                'foto' => null,
                'kode_guru' => 'JM',
                'nama_guru' => 'JIDDAN ZULFA MAULANA, S.Ag',
                'nip' => null,
                'nuptk' => null,
                'nik' => '3329161802000004',
                'status' => 'GTY',
                'tahun_sertifikasi' => null,
                'jenis_kelamin' => 'Laki - Laki',
                'pendidikan' => 'S1',
                'lulusan' => '2025',
                'jurusan' => 'STUDI AGAMA-AGAMA',
                'tahun_lulus' => '2025',
                'rt' => '6',
                'rw' => '3',
                'desa' => 'Kubangwungu',
                'kecamatan' => 'ketanggungan',
                'kabupaten' => 'Brebes',
                'provinsi' => 'Jawa Tengah',
                'jalan' => 'Kubangwungu',
                'alamat' => 'Kubangwungu, Rt 6, Rw 3, Desa Kubangwungu, Kecamatan ketanggungan, Kabupaten Brebes',
                'no_hp' => '6282313062195',
                'agama' => 'Islam',
                'tempat_lahir' => 'Brebes',
                'tanggal_lahir' => '18/02/2000',
                'tmt_mengajar' => null,
            ],
            [
                'user_id' => null,
                'kelas_id' => null,
                'foto' => null,
                'kode_guru' => 'AH',
                'nama_guru' => 'AMELIYA NUR HIKMAH, A.Md.Ds',
                'nip' => null,
                'nuptk' => null,
                'nik' => '3329166411020000',
                'status' => 'GTY',
                'tahun_sertifikasi' => null,
                'jenis_kelamin' => 'Perempuan',
                'pendidikan' => 'D3',
                'lulusan' => null,
                'jurusan' => 'DKV',
                'tahun_lulus' => '2024',
                'rt' => '2',
                'rw' => '3',
                'desa' => 'Kubangwungu',
                'kecamatan' => 'ketanggungan',
                'kabupaten' => 'Brebes',
                'provinsi' => 'Jawa Tengah',
                'jalan' => 'Kubangwungu',
                'alamat' => 'Kubangwungu, Rt 2, Rw 3, Desa Kubangwungu, Kecamatan ketanggungan, Kabupaten Brebes',
                'no_hp' => '6285879161441',
                'agama' => 'Islam',
                'tempat_lahir' => 'Brebes',
                'tanggal_lahir' => '24/11/2002',
                'tmt_mengajar' => null,
            ],
            [
                'user_id' => null,
                'kelas_id' => null,
                'foto' => null,
                'kode_guru' => 'MA',
                'nama_guru' => 'M. ANWAR,',
                'nip' => null,
                'nuptk' => '2036398819800200',
                'nik' => '3329163006980004',
                'status' => 'GTY',
                'tahun_sertifikasi' => null,
                'jenis_kelamin' => 'Laki - Laki',
                'pendidikan' => 'SMA',
                'lulusan' => '2016',
                'jurusan' => 'IPA',
                'tahun_lulus' => '2016',
                'rt' => '7',
                'rw' => '3',
                'desa' => 'Kubangwungu ',
                'kecamatan' => 'Ketanggungan ',
                'kabupaten' => 'Brebes',
                'provinsi' => 'Jawa Tengah',
                'jalan' => 'Kubangwungu',
                'alamat' => 'Kubangwungu, Rt 7, Rw 3, Desa Kubangwungu , Kecamatan Ketanggungan , Kabupaten Brebes',
                'no_hp' => '6283816438878',
                'agama' => 'Islam',
                'tempat_lahir' => 'Brebes',
                'tanggal_lahir' => '30/06/1998',
                'tmt_mengajar' => '01/07/2022',
            ],
            [
                'user_id' => null,
                'kelas_id' => null,
                'foto' => null,
                'kode_guru' => 'UN',
                'nama_guru' => 'UNJI NAFISAH,',
                'nip' => null,
                'nuptk' => '20363988',
                'nik' => '3329166308980002',
                'status' => 'GTY',
                'tahun_sertifikasi' => null,
                'jenis_kelamin' => 'Perempuan',
                'pendidikan' => 'SMA',
                'lulusan' => '2016',
                'jurusan' => null,
                'tahun_lulus' => '2016',
                'rt' => '5',
                'rw' => '3',
                'desa' => 'Kubangwungu',
                'kecamatan' => 'Ketanggungan',
                'kabupaten' => 'Brebes',
                'provinsi' => 'Jawa Tengah',
                'jalan' => 'Kubangwungu',
                'alamat' => 'Kubangwungu, Rt 5, Rw 3, Desa Kubangwungu, Kecamatan Ketanggungan, Kabupaten Brebes',
                'no_hp' => null,
                'agama' => 'Islam',
                'tempat_lahir' => 'Brebes',
                'tanggal_lahir' => '23/08/1998',
                'tmt_mengajar' => '17/07/2017',
            ],
            [
                'user_id' => null,
                'kelas_id' => null,
                'foto' => null,
                'kode_guru' => 'BJ',
                'nama_guru' => 'BEJO SISWADI,',
                'nip' => null,
                'nuptk' => '2036398816800100',
                'nik' => '3329160902680002',
                'status' => 'GTY',
                'tahun_sertifikasi' => null,
                'jenis_kelamin' => 'Laki - Laki',
                'pendidikan' => 'SMA',
                'lulusan' => '1996',
                'jurusan' => 'ipa',
                'tahun_lulus' => '1996',
                'rt' => '4',
                'rw' => '3',
                'desa' => 'Kubangwungu',
                'kecamatan' => 'ketanggungan',
                'kabupaten' => 'Brebes',
                'provinsi' => 'Jawa Tengah',
                'jalan' => 'kubangwaungu',
                'alamat' => 'kubangwaungu, Rt 4, Rw 3, Desa Kubangwungu, Kecamatan ketanggungan, Kabupaten Brebes',
                'no_hp' => null,
                'agama' => 'Islam',
                'tempat_lahir' => 'Brebes',
                'tanggal_lahir' => '09/02/1968',
                'tmt_mengajar' => '02/07/2016',
            ],
        ];
        foreach ($guruArray as $guru) {
            $dataGuru = Detailguru::where("kode_guru", $guru['kode_guru'])->first();
            echo "{{$guru['kode_guru']}}";
            $dataGuru->update([
                'nuptk' => $guru['nuptk'],
            ]);
        }
        /*
        foreach ($guruArray as $guru) {
            Detailguru::updateOrCreate(
                ['kode_guru' => $guru['kode_guru']], // cari berdasarkan ini
                [
                    'nuptk' => $guru['nuptk'],
                    ['kode_guru' => $guru['kode_guru']]
                ] // update kolom ini (atau tambah yang lain)
            );
        }
            */

        $this->info("Command 'UpdateDetailguruCommand' berhasil dijalankan.");
    }
}
